-- Create feedback table in kb schema
-- Execute this in your Neon database to create the feedback storage

CREATE TABLE IF NOT EXISTS kb.feedback (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    rating VARCHAR(10) NOT NULL CHECK (rating IN ('positive', 'negative')),
    comment TEXT,
    page_url VARCHAR(500) NOT NULL,
    page_title VARCHAR(200) NOT NULL,
    user_agent TEXT,
    ip_address VARCHAR(45), -- IPv4: 15 chars, IPv6: 45 chars max
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create indexes for performance
CREATE INDEX IF NOT EXISTS idx_feedback_created_at ON kb.feedback (created_at);
CREATE INDEX IF NOT EXISTS idx_feedback_page_url ON kb.feedback (page_url);
CREATE INDEX IF NOT EXISTS idx_feedback_rating ON kb.feedback (rating);

-- Grant permissions (adjust as needed for your setup)
-- GRANT SELECT, INSERT ON kb.feedback TO neondb_owner;
-- GRANT USAGE, SELECT ON SEQUENCE kb.feedback_id_seq TO neondb_owner;